### ISSUE TITLE
Package the new test for merging?

### ISSUE THREAD

**Issue by cunha** [ignitz/2016_2_dcc605#1]
Any chance we can package the new `test.c` file for merging into the main repository? Seems like a cool test. What I would like to have is a `test7.sh` file that runs the test (e.g., it may create the text file with the list of files by running `ls` before running the test binary itself).

If you do package, please add your names to the files so you get credit for it.

https://github.com/ignitz/2016_2_dcc605/blob/master/TP2/dcc605fs-assignment/test.c#L96

Only 5 lines using XGH? And commented out? Premium!

**Comment by ignitz** [comment]
Sure. Do I have to submit the file in your repository or just the permission (in this case it is already yes)?

**Comment by cunha** [comment]
You can make a pull request, send a patch, or just send me the files in an
e-mail (I can copy them and push to the repo). Whatever is easier for you,
really. And thanks for the effort.
